### PR TITLE
Updating es.yml to call attention to a few translation errors

### PR DESCRIPTION
**Pull request by danielmcq**
I understand that the language translation YML files are generated, but I noticed a few inconsistencies in the es translation, so I'm doing this pull request so they get visibility.

### CODE REVIEW

**Comment by claydiffrient** [comment]
@danielmcq Thanks for the PR.  I'm going to send these suggestions to our translators.  But since we can't actually merge onto the auto-generated file, I'm going to close the PR.

**Comment by simonista** [comment]
Also, if you're interested in fixing the issue at the source, you can create an account on transifex (https://www.transifex.com/projects/p/canvas-lms/resource/canvas-lms/) and suggest fixes there directly.

**Comment by danielmcq** [comment]
Thanks. I'll head over to that page and make the suggestions.

**Comment by claydiffrient** [comment]
@danielmcq I'm told that those translations have been updated in Transifex and will be replicated into the Canvas codebase.

**Pull request closed without merging**
