### PR TITLE
Fix some grammar

### PR DESCRIPTION
**Pull request by fadedmax**
this would look a bit nicer, its just the exporting, not that big of a change, but it would look nicer then the current all lowercase

### CODE REVIEW

**Comment by fadedmax** [comment]
Sorry about the bad commit message... not the most descriptive, its just a minor change however.

**Comment by spencerolson** [comment]
Hi @fadedmax thanks for the contribution! And sorry for the late response here. I just brought this up with the Product team and they have a couple requests:
- Can you change "awhile" to "a while"?
- In the sentence below the progress bar on the same page, can you change "This can take awhile for large courses" to "This can take a while for large courses" (file for that change is `app/views/content_exports/index.html.erb`)

**Comment by scoutskylar** [comment]
"Awhile" is an adverb, and "a while" is a noun phrase. In this context, "awhile" is the grammatically correct option. (Of course, very few people would care, but I think the requested changes should not be made.)

**Comment by spencerolson** [comment]
@scoutskylar we decided on the two-word form here because the Chicago Manual of Style [recommends it](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Usage/faq0016.html): ```the adverb awhile means for a while, which clearly should not follow will take (compare stay awhile, which survives expansion to stay for a while)```

**Comment by scoutskylar** [comment]
I recreated this pull request to resolve conflicts (since the changed file was moved) and made the requested changes in a new pull request: https://github.com/instructure/canvas-lms/pull/2010

**Comment by spencerolson** [comment]
> I recreated this pull request to resolve conflicts (since the changed file was moved) and made the requested changes in a new pull request: #2010

Thank you! I will take a look.

**Comment by fadedmax** [comment]
Hi there! Apologies for not taking action. Was locked out of my 2FA codes for awhile due to some technical problems

Closing in favor of #2010

**Pull request closed without merging**
