### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Skylertodd**
Did you mean to pass in the 2 previous parameters? There was not a third parameter to be passed in..

### CODE REVIEW

**Comment by tierra** [comment]
I wouldn't mind just explicitly naming both files again:
```chmod 777 mkmf.log .listen_test```

That would prevent someone from making this mistake again.

**Comment by Skylertodd** [comment]
that would work. Not sure how to progress with this edit since I am newer to contributing on github

**Comment by tierra** [comment]
Looking good, I know this isn't a code contribution, but our CLAhub test will still require you to sign the CLA regardless. Past that I'll make sure this gets applied.

**Comment by tierra** [comment]
Closing due to inactivity.

**Pull request closed without merging**
