### PR TITLE
Removes some harmful language in specs

### PR DESCRIPTION
**Pull request by rthbound**
The primary purpose of this change is to eliminate a paradigm of "student is slave and teacher is boss".

Other small changes:
- Worthless loser?
- Soften a somewhat disparaging comment regarding a perceived code smell

### CODE REVIEW

**Comment by simonista** [comment]
Hey @rthbound , thanks for making this change, this is great. I'll get it run through our CI pipeline today.

**Comment by rthbound** [comment]
Thank you @simonista -- I was hoping the change would be accepted.

**Comment by simonista** [comment]
Just a quick update here, we have a campsite rule that checks all specs touched by a commit, and two of the specs touched here are sometimes too slow, so I'm looking into how to speed them up.

**Comment by rthbound** [comment]
@simonista which two? maybe I could have a look. Is there a chance these two slow ones may be covered elsewhere (and could be removed)?

**Pull request closed without merging**
