### PR TITLE
Add user_ids to quiz statistics endpoint

### LINKED ISSUE #1522: Quiz Statistics endpoint doesn't include user ids
### Summary:
The [quiz statistics endpoint](https://canvas.instructure.com/doc/api/quiz_statistics.html#method.quizzes/quiz_statistics.index) includes a `user_names` field for each answer but doesn't include the student ids (making it impossible to uniquely identify which responses were chosen by students). This seems like an oversight considering that student names are already present.

### PR DESCRIPTION
**Pull request by andrew-gardener**
Fixes #1522

### CODE REVIEW

**Comment by simonista** [comment]
Cool, thanks @andrew-gardener, I'll get this run through our full test suite.

**Comment by jlongland** [comment]
Just checking in to see how it's going with the testing? We're working on a project w/ an instructor and this is a blocker for us. We're aiming for a January launch - just wondering if it's likely we'll see this through to a prod deploy by then?

**Comment by simonista** [comment]
Looks like we had some infrastructure issues with the full test suite, I'll re-run things and see if I can get it passing.

It needs to merge by EOD tomorrow to be in production by the end of the year, otherwise it'll be there 1/15/19.

**Comment by simonista** [comment]
Okay, tests are passing, and it's in the queue for QA.

**Comment by andrew-gardener** [comment]
Thanks a bunch getting this moved along!

**Comment by andrew-gardener** [comment]
@simonista Any word from QA? It would be very helpful to get this in before next term

**Comment by andrew-gardener** [comment]
err, was there a reason it was closed without merging? Was there something wrong?

**Comment by vimalloc** [comment]
It was merged here: https://github.com/instructure/canvas-lms/commit/51a25db1b8cef0cd6e5a2b8812e8ccda3b026357. It's just the way our gerrit -> github works, it wont show up as a merge in this pull request :+1:

**Comment by andrew-gardener** [comment]
Okay, didn't realize that's what happened.

Thanks a bunch!

**Pull request closed without merging**
