### PR TITLE
Fix typo in public/file_removed/file_removed.pdf

### PR DESCRIPTION
**Pull request by christopher-b**
I'm submitting this PR at the request of @omarkhan in #1255. However, I would imagine that this PDF was generated from a source file in Illustrator or similar. In that case, the source file should be updated, and the PDF re-generated. Either way, here's a fixed version of the image. 

image

### CODE REVIEW

**Comment by christopher-b** [comment]
I signed the CLA a long time ago, under my employer OCAD University.

**Comment by bootstraponline** [comment]
Hi, thanks for the pull request! It looks like there are two issues:

1) The commit isn't associated with your github account
2) The CLA isn't signed. We recently migrated to a digital CLA system to automate the signing process. It should be relatively painless.

**Comment by christopher-b** [comment]
Should be sorted out now, thanks.

**Comment by bootstraponline** [comment]
Great. To help the reviews, I added a screenshot of the change.

**Comment by bootstraponline** [comment]
https://github.com/instructure/canvas-lms/commit/8335f8bdf1deab5c67f92cb3d89f642eb5345261 has been merged to master. The file was generated from the original source.

**Pull request closed without merging**
