### PR TITLE
Add a button to enter student view to the course home page

### PR DESCRIPTION
**Pull request by tbodt**

### CODE REVIEW

**Comment by simonista** [comment]
Hi @tbodt, thanks for the pull request.  Let me find the correct product owner and see if this is something we want to pull in.

**Comment by tbodt** [comment]
There is the question of where is the best place to put the button. This PR would only make it available on the home page, and it's common to be on pages other than the home page. Maybe it should go at the bottom of the left sidebar, under a divider line?

**Comment by tbodt** [comment]
@simonista any update on this?

**Comment by tbodt** [comment]
A similar proposal got about 300 votes back in 2015 and is still in the "product radar" stage. There are a number of recent comments saying this would be really nice to have.

**Comment by simonista** [comment]
Hey @tbodt, sorry for the lack of response. I'll ping our product team again.

**Comment by simonista** [comment]
got the +1 from our product team, we'll get this pulled in a run through tests and looked at by QA.  thanks for the contribution!

**Comment by spencerolson** [comment]
Hi @tbodt , thanks for your contribution! Your commit has been merged into the `master` branch, and can be found here: https://github.com/instructure/canvas-lms/commit/db109b9ef88235f68b582a7ae3325c44e6821edd

Thanks,
Spencer

**Pull request closed without merging**
