### PR TITLE
Fix unintended group membership deletion

### PR DESCRIPTION
**Pull request by patchin**
Prevents removal of user from unrestricted groups when the user is enrolled in more than one section of a course. The previous code assumes that a student is enrolled in at most one section of a course. The new code checks for multiple enrollments.

This fixes issues #235224 and #630214 reported on help.instructure.com.

Test plan:
- add the user to multiple sections of a course
- add the user to an unrestricted group of the course
- delete the user from one section
- confirm that the user is still in the group

--

NOTE: We have a signed CLA for all of Simon Fraser University (SFU) on file.

### CODE REVIEW

**Comment by ccutrer** [comment]
Update - this has passed automated testing, and has a +1 code review (requires a +2), so is waiting for a +2 and QA approval

**Comment by patchin** [comment]
Thanks for the update!

**Comment by patchin** [comment]
Hi, any update on this pull request? Thanks.

**Comment by ccutrer** [comment]
Nothing. I'll try and kick some people into checking it out. Thanks for the reminder.

**Comment by simonista** [comment]
Just pinged a few more people to look at this, hopefully we'll get some traction on it soon.  Sorry for the delay.

**Comment by patchin** [comment]
No problem. Thanks!

**Comment by patchin** [comment]
Yay! Thanks!

**Comment by srivatsats** [comment]
Hi

We are looking to understand the infrastructure requirements to support 500
Concurrent users on Canvas. Con someone guide us please based on your
experience? We are on AWS and Iam primarily looking to understand how many
EC2 servers we will need and the configuration of each server VM (small,
medium, large, Xlarge etc)

Would highly appreciate your help.

Thanks, 

Srivatsa TS
Vice President ­ Technology Products

SmartOn Learning
Mobile : +91 99800 69633
email  : srivatsa@smarton.co <mailto:srivatsa@smarton.co>
Skype : srivatsats 
http://www.smarton.co/ <https://smarton.co/>



From:  Patrick Chin <notifications@github.com>
Reply-To:  instructure/canvas-lms
<reply+006aec4401a86cb06912f4e572996e32d37812a8631a139792cf000000011122cb839
2a169ce03541096@reply.github.com>
Date:  Thursday, 19 March 2015 11:08 pm
To:  instructure/canvas-lms <canvas-lms@noreply.github.com>
Subject:  Re: [canvas-lms] Fix unintended group membership deletion (#575)


Yay! Thanks!

‹
Reply to this email directly or view it on GitHub
<https://github.com/instructure/canvas-lms/pull/575#issuecomment-83689901> .

**Comment by patchin** [comment]
@srivatsats Here's some info that might help: https://groups.google.com/forum/#!topic/canvas-lms-users/CqNpiXtNN-Q

**Pull request merged**
