### PR TITLE
Clarify suggestions for using a supported bundler version

### PR DESCRIPTION
**Pull request by rwstauner**
This attempts to help clarify the steps necessary to resolve issues like #855.

Always suggest installing a supported version, and if necessary suggest working around a newer version.

```
💥  bundle check
Bundler version 1.8.0 is required; you're currently running 1.7.0.

Install a supported version: `gem install bundler -v 1.11.2`.

💥  gem install bundler -v 1.11.2
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
Parsing documentation for bundler-1.11.2
Installing ri documentation for bundler-1.11.2
Done installing documentation for bundler after 5 seconds
1 gem installed

💥  bundle check
Resolving dependencies...............
The Gemfile's dependencies are satisfied

💥  gem install bundler
Fetching: bundler-1.12.5.gem (100%)
Successfully installed bundler-1.12.5
Parsing documentation for bundler-1.12.5
Installing ri documentation for bundler-1.12.5
Done installing documentation for bundler after 5 seconds
1 gem installed

💥  bundle check
Bundler version 1.8.0 is required; you're currently running 1.12.5.

Install a supported version: `gem install bundler -v 1.11.2`.

Then prefix 'bundle' commands with '_1.11.2_' like this: `bundle _1.11.2_ check`
or uninstall this newer version with `gem uninstall bundler -v 1.12.5`.

[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `_before.rb`: exit. Bundler cannot continue.

 #  from /data/raptor/src/github/canvas-lms/Gemfile.d/_before.rb:48
 #  -------------------------------------------
 #    warn message
 >    exit 1
 #  end
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /data/raptor/src/github/canvas-lms/Gemfile.d/_before.rb:48
 #  -------------------------------------------
 #   >   #  
 #  -------------------------------------------

💥  bundle _1.11.2_ check
Resolving dependencies................
The Gemfile's dependencies are satisfied
```

### CODE REVIEW

**Comment by claydiffrient** [comment]
@rwstauner sorry for the delay on this. Unfortunately the commit message doesn't meet the standards outlined in our CONTRIBUTING.md. If you'd update, we'd get this pulled in and get the code review process started.

**Comment by rwstauner** [comment]
np.  How's that?

I'm traveling soon so might not respond for a while.

Thanks!

**Comment by tierra** [comment]
This is looking pretty solid to me, and the commit message has a good description and test plan. It'd be nice to get this rebased on latest master (to resolve merge conflict), but I'm happy to push this forward after.

**Comment by rwstauner** [comment]
@tierra this patch reworded a block of code that has since been removed: b979636be34ccfaa684e06632b66f567e3436b0e
so i guess we should just close it.
thanks, though.

**Comment by tierra** [comment]
Ah, I didn't spot that one go through, thanks anyway.

**Pull request closed without merging**
