### PR TITLE
Update allowances for certain LTI iframes

### PR DESCRIPTION
**Pull request by conradbeach**
We embed our LTI tool inside of Canvas pages. One of the features of our LTI tool requires microphone permissions from the client in order to work. However, the code that generates the `<iframe />` HTML that our tool is embedded in does not allow us to request microphone permissions because the `allow` attribute on the `<iframe />` does not include microphone in the list.

In [this commit](https://github.com/instructure/canvas-lms/commit/fcae49e4e556a07c0a9b49ee6fe25fd914ab1058), all other (presumably all other) LTI iframes were given the following value for the `allow` attribute.
```
geolocation; microphone; camera; midi; encrypted-media
```
(Minor changes to this list of permissions have been made since the original addition in that commit.)

This branch updates the iframe used to embed LTI tools and other content items so that the iframe has the same list of values for its `allow` attribute as other iframes have. (As set in `Lti::Launch.iframe_allowances`.)

This will increase uniformity across LTI iframes and will allow full functionality for LTI tools embedded on pages.

**Before**
```
<iframe style="width: 100%; height: 800px;" src="www.example.com" title="Some Title" allowfullscreen="allowfullscreen" webkitallowfullscreen="webkitallowfullscreen" mozallowfullscreen="mozallowfullscreen" allow="autoplay *" width="100%" height="800px"></iframe>
```

**After**
```
<iframe style="width: 100%; height: 800px;" src="www.example.com" title="Some Title" allowfullscreen="allowfullscreen" webkitallowfullscreen="webkitallowfullscreen" mozallowfullscreen="mozallowfullscreen" allow="geolocation; microphone; camera; midi; encrypted-media; autoplay" width="100%" height="800px"></iframe>
```
(Chrome and blank user agents have ` *` appended to each value in the `allow` list.)

### CODE REVIEW

**Comment by conradbeach** [comment]
@djbender Any chance I could get a review on this?

**Comment by abtrumpet** [comment]
@conradbeach We need this functionality, as well. Sadly, it seems unlikely you will get any reviewer as Instructure just laid off a large portion of their developers.

**Comment by westonkd** [comment]
Thanks for your contribution @conradbeach !

We've pulled this PR into our team's current sprint. We should have some feedback for you within two weeks, but likely sooner.

**Comment by conradbeach** [comment]
@westonkd Thanks!

**Comment by westonkd** [comment]
@conradbeach Your changes have been merged to the master branch: https://github.com/instructure/canvas-lms/commit/315f85aaefae9bb3c947a895ff28b662301a2160

Thank you for your contribution!

**Comment by conradbeach** [comment]
Awesome. Thank you.

**Pull request closed without merging**
