### PR TITLE
updated package.json

### PR DESCRIPTION
**Pull request by Droobledores**
updated package.json to fix security patches for dependencies.

### CODE REVIEW

**Comment by bootstraponline** [comment]
Hi there! Thank you for your pull request! We don't accept PRs to the stable branch, as outlined in the contributing.md file. Also we wouldn't want to downgrade the packages in Canvas. If you have more details on the security concern, open a GitHub issue and I'll ping our security team.

**Comment by Droobledores** [comment]
Sorry about that. Also, I did not realize that it downgraded the packages. I only saw the security alerts.

**Comment by bootstraponline** [comment]
Where did you see the security alerts? I'm happy to check to see if we have a plan to fix this.

**Comment by Droobledores** [comment]
I saw the security alerts on the front page of my fork of the repository. Then, it brought me to the Dependency graph page in the insights tab.

**Comment by Droobledores** [comment]
Do you want me to change the packages' versions back to what they were and change it to a different branch?

**Comment by bootstraponline** [comment]
PRs should target the master branch. Yeah, the downgrades should be reverted. I'm checking to see if we have an existing process around this.

**Comment by bootstraponline** [comment]
I checked. If you want to submit a new PR to master with only the security fixes, we'll review the code.

**Comment by Droobledores** [comment]
So I create a pull request for the stable branch?

**Comment by bootstraponline** [comment]
> So I create a pull request for the stable branch?

Pull requests should target the master branch as outlined in the contributing.md file. Commits aren't made to stable directly.

**Pull request closed without merging**
