### PR TITLE
Docs review

### PR DESCRIPTION
**Pull request by phil-davis**
General typo and grammar adjustments.

### CODE REVIEW

**Comment by phil-davis** [comment]
@maths22 any interest in this?
Should I rebase and resolve the conflicts? Or close?

**Comment by maths22** [comment]
Sorry for the delay.  This looks good and we'll get it pulled it, but would you be able to un-reformat those tables and resolve the merge conflicts first?

**Comment by phil-davis** [comment]
@maths22 rebased, conflicts resolved, tables fixed. Please review.

**Comment by phil-davis** [comment]
@maths22 I rebased again to keep this up-to-date. It should be easy to review and merge.

**Comment by phil-davis** [comment]
No response. I suppose that community contributions are not wanted.

**Pull request closed without merging**
