### PR TITLE
BigBlueButton conference sends an extra meta-parameter required for the integration with Arc

### PR DESCRIPTION
**Pull request by jfederico**
Summary:
Extension for BigBluebutton recordings ready post-processing that enables the integration with Arc.

Description:
The only update is to the big_blue_button model for adding a new meta parameter that includes the user  email in [RFC2822](https://tools.ietf.org/html/rfc2822#section-3.4) format. This parameter is required in order to match the user accounts between Canvas and Arc.

Test Plan:
https://youtu.be/3qmmpmAaoF0
Follow the same steps that in the video:

1. Configure the BBB server to be used by the Plugin. Make sure the recordings are enabled.
2. Go to the Course/Conferences
3. Create a Conference. Enable recordings. Save
4. Start the conference. This will send you to BBB. You can confirm that the recording feature was enabled by starting the recording, although it is not necessary.
5. Go to the tool called api-mate. https://bigbluebutton.org/api-mate/
6. Replace the default credentials in api-mate with the ones for Instructure
7. Make sure there is no meetingID set in the corresponding box
8. Just go to getMeetings and check the XML response. In the metadata, the parameter "canvas-recording-ready-user" should be included with an encrypted string as the value.

```
<canvas-recording-ready-user>
QkJJT05aeVRzMGI1aEpCM2dwQXBhb2JyWW5yZzVvK1VvRHB5elVMamxRcjcxVkRVTUpUM2trTUNhUGloV1NMdGhrRWRYSkhkc1ZxRFpnOHJxNkxuSzJqQXQ4bVhGZFhSa3lad0Zwc1RIeUxhSG1LbTA4U3BHcUlFQlJ4TEZpYWZVeG5LUW4zL1Bna2VWcUpjc2QzZnlFWTh0ZVYrRUVUM0c1bXM0b3lvWk9zSzRMY1pvMTBYdXNOZ3ZUU3BscDFLLS1SUnArbzRiQUh6Z3Q5U25PaGtISnpnPT0=--875a6374ca7b9fe7804e91aec6456e5e9fc06c86
</canvas-recording-ready-user>
```

9. The string can be decoded through the rails console using the BBB secret
```
key = ActiveSupport::KeyGenerator.new('secret').generate_key('secret', 32)
crypt = ActiveSupport::MessageEncryptor.new(key)
padded_user_email = crypt.decrypt_and_verify('QkJJT05aeVRzMGI1aEpCM2dwQXBhb2JyWW5yZzVvK1VvRHB5elVMamxRcjcxVkRVTUpUM2trTUNhUGloV1NMdGhrRWRYSkhkc1ZxRFpnOHJxNkxuSzJqQXQ4bVhGZFhSa3lad0Zwc1RIeUxhSG1LbTA4U3BHcUlFQlJ4TEZpYWZVeG5LUW4zL1Bna2VWcUpjc2QzZnlFWTh0ZVYrRUVUM0c1bXM0b3lvWk9zSzRMY1pvMTBYdXNOZ3ZUU3BscDFLLS1SUnArbzRiQUh6Z3Q5U25PaGtISnpnPT0=--875a6374ca7b9fe7804e91aec6456e5e9fc06c86')
padded_user_email.strip
```

Development ID:
https://github.com/blindsidenetworks/canvas-lms/issues/22

Internall ID:
COMMS-604

### CODE REVIEW

**Comment by bootstraponline** [comment]
This PR is waiting on https://github.com/instructure/canvas-lms/pull/1079 to merge first.

**Comment by jfederico** [comment]
- Updated code up to commit 52c8376 which is the current for PR #1079.
- Changed the way the recording-ready-user us determined
- Added spec for testing the the new method recording_ready_user in the model big_blue_button_conference

**Comment by bootstraponline** [comment]
This PR is being tracked internally as `COMMS-604`

**Comment by bootstraponline** [comment]
Code has been updated.

**Comment by bootstraponline** [comment]
Product approved.

**Comment by bootstraponline** [comment]
Fix has been merged.

**Pull request closed without merging**
