### PR TITLE
Augment module item completion requirements with 'mark as done'.

### PR DESCRIPTION
**Pull request by kjellm**
Hi

I am working on a project for the Norwegian government aiming to
create a MOOC (based on Canvas) with several courses for continuing
education of teachers of mathematics.

The courses are module based and relies heavily on the module item
requirements to enable students to track progress. This works great
for the most part, but there is missing a good mechanism for students
to keep track of progress with regards to articles (wiki pages). The
closest thing is the 'must view' requirement, but this does not cater
to students who needs multiple reading sessions before they feel they
are done.

This requirement can also be used on assignments that are purely for
self studying.

This pull-request is to be regarded as a prototype of this 'mark as
done' functionality. My motives for creating an early pull-request is
to hopefully get your feedback on, primarily: Whether this is
functionality you are interested in merging into the project? And
secondarily: Is my implementation close to how you would like this
feature implemented? I would really appreciate any feedback on how
this functionality should be implemented from your point of view. I am
more than willing to change the code accordingly.

Known issues with the prototype:

  - need to write tests.
  - need to document new API-endpoints.
  - fix ugly controller code and duplication.
  - need to do UI design.
  - unchecking the 'mark as done' checkbox does not work (not done
    implementing API endpoint).

Kjell-Magne

### CODE REVIEW

**Comment by claydiffrient** [comment]
@kjellm Thanks for the pull request.  I'll make sure this gets put in front of our product team.  We can then decide if this is a feature we want to implement.  If all goes well there, I'll get this in front of the right people on our engineering team to determine the next steps forward on this. Just glancing over the code, it doesn't look too bad, and your comments are helpful to see what still needs to be done.

**Comment by kjellm** [comment]
@claydiffrient Do you have any news regarding this pull request?

**Comment by claydiffrient** [comment]
@kjellm Sorry, nothing concrete to report at the moment.  I'll ping the product team again and see what's happening.

**Comment by kjellm** [comment]
@claydiffrient thanks, much appreciated.

**Comment by kjellm** [comment]
My todo-list is now down to:
 - writing tests (I have not succeeded in getting the test suite to run in my development environment yet)
 - UI design

**Comment by claydiffrient** [comment]
@kjellm I've spoken with our product team and I've received approval this far for the feature.  When you have things completed let me know and we'll take a look and double check everything to make sure it checks out.  In the mean time, do you have a contributor agreement on file with us? (https://github.com/instructure/canvas-lms/blob/stable/CONTRIBUTING.md)

**Comment by kjellm** [comment]
@claydiffrient Thanks, that is great news! I filed a contributor agreement in advance of my previous pull request (#539).

**Comment by kjellm** [comment]
@claydiffrient: Not sure what happened with this pull request (suddenly 774 files changed). So I'm closing this and creating a new one. Sorry for the inconvenience.

**Pull request closed without merging**
