### PR TITLE
Adds textarea to be except from focusOnAssignments

### PR DESCRIPTION
**Pull request by dabjulmaros**
Adds textarea to be except from focusOnAssignments. In the live version of canvas in the assignments page if a user tries to type the letter J into a textarea element, the element loses focus, and the uses is unable to type.  

Closes issues #1308.

Test Plan:
-Go to any assignments page.
-Make sure assignments are still being indexed when pressing the letter J.
-Make sure the letter J can be inputted into input elements.
-Makes sure the letter J now can be inputted into textarea elements.

CNVS-42858

### CODE REVIEW

**Comment by bootstraponline** [comment]
Hi,

Thanks for submitting a pull request to Canvas LMS! Sorry for the slow response. We're preparing for [Instructurecon](https://www.canvaslms.com/news/instructurecon/) so there are limited resources to review open source contributions right now.

It'd be awesome if you could record a short video that demonstrates the problem/solution. I can then bring that to the product team for prioritization. Also it looks like there are some conflicts that need to be resolved.

Thanks!

**Comment by dabjulmaros** [comment]
Here is a link to a google drive containing the video: https://drive.google.com/file/d/1xGjeJ0e73Wf3uAV0F4DNGaHEUAMGjvB7/view?usp=sharing
I dont see any more conflicts so hope that helps. The video only shows the issue. 
Hope that helps.

**Comment by bootstraponline** [comment]
Perfect, thanks!

**Comment by bootstraponline** [comment]
I talked with the QA team and we're figuring out the next steps for the bug fix. The video was helpful in understanding the issue.

**Comment by dabjulmaros** [comment]
Awesome, Thanks.

**Comment by bootstraponline** [comment]
An internal JIRA ticket has been created (CNVS-42858), that will go through the regular sprint planning process. I don't have an ETA on when the fix will be reviewed, however we're tracking it now.

**Comment by dabjulmaros** [comment]
Hi, 
I was checking the current release of beta, and the issue is fixed. Should I keep this open until the fix goes into the live version of canvas, or is ok to close it now?

**Comment by bootstraponline** [comment]
I think it's good to close now that the bug has been fixed. Thanks for letting me know the issue has been resolved on beta.

**Pull request closed without merging**
