### PR TITLE
Augment module item completion requirements with 'mark as done' (Take 2)

### PR DESCRIPTION
**Pull request by kjellm**
See pull request #571

### CODE REVIEW

**Comment by kjellm** [comment]
@claydiffrient: I am done with everything on my TODO list. Can you take a look at the code?

**Comment by kjellm** [comment]
@claydiffrient btw. I have a changed employer since I signed the contributor agreement, should I sign a new one?

**Comment by claydiffrient** [comment]
@kjellm Go ahead and sign a new CLA just to be safe.  I'll pull this down and take a look today.

**Comment by claydiffrient** [comment]
@kjellm I've been trying this morning to get your PR pulled down and into our internal testing suite.  It's proven to be a little difficult.  Would you mind cleaning up the commits some?  If you can remove the merge commits and perhaps rebase on top of the latest master instead, that would make things a lot easier on our end.  Thanks!

**Comment by kjellm** [comment]
@claydiffrient Created a new pull request with all the changes gathered into a single commit on top of latest master (See #510).

**Comment by kjellm** [comment]
> Go ahead and sign a new CLA just to be safe.

Done

**Pull request closed without merging**
