### PR TITLE
[.rubocop.yml] Upgraded namespaces for compatability with latest rubocop

### PR DESCRIPTION
**Pull request by SamuelMarks**
It might also be a good idea to sort this YAML file, but I didn't want to do this without your approval.

Working with rubocop version 0.79.0.

### CODE REVIEW

**Comment by simonista** [comment]
Hi @SamuelMarks , sorry to be so slow responding to this.

We currently have rubocop pinned at 0.52.1, will these changes still work with that version? (see https://github.com/instructure/canvas-lms/blob/master/Gemfile.d/test.rb#L41)

**Comment by SamuelMarks** [comment]
Give it a shot?

**Comment by simonista** [comment]
I think if that's the attitude, we'll probably turn this down for now. We're still evaluating if/how we want to move forward with Rubocop, and so in order to accept this I'd need to know for sure that it works with our current version.

**Comment by SamuelMarks** [comment]
@simonista I've merged in master, and carefully ensured that only the changes that are still valid were added to the `.rubocop.yml` file.

**Pull request closed without merging**
